spring:
  profiles:
    default: localmysql
  flyway:
    enabled: false
  security:
    user:
      name: user1
      password: password

logging:
  level:
    org.apache.commons.beanutils.ConvertUtils: "info"
    org.hibernate.orm.deprecation: "error"